<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <VersionPrefix Condition=" '$(BuildVersion)' == '' ">0.0.1-local</VersionPrefix>
        <VersionPrefix Condition=" '$(BuildVersion)' != '' ">$(BuildVersion)</VersionPrefix>
        <PackageId>SystemUptimeTracker.Common</PackageId>
        <AssemblyName>SystemUptimeTracker.Common</AssemblyName>
        <Company>Michael Carey</Company>
        <Description>
            Shared library for the System Uptime Tracker application.
        </Description>
        <PackageTags>System Uptime Tracker</PackageTags>
        <Title>System Uptime Tracker Common Library</Title>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);1572;1573;1591</NoWarn>
        <Configurations>Debug;Release;Development;Testing;Staging;Production</Configurations>
        <RootNamespace>SystemUptimeTracker.Common</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Include="readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ff-dotnet-server-sdk" Version="1.7.6" />
        <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Compliance.Redaction" Version="10.9.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
        <PackageReference Include="Microsoft.FeatureManagement" Version="4.7.0" />
        <PackageReference Include="Microsoft.VisualStudio.SlowCheetah" Version="4.0.50">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
    </ItemGroup>


</Project>
