version: 2

updates:
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: monthly
    groups:
      backward-compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    groups:
      backward-compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      backward-compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
