<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>SystemUptimeTracker.Data</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);1572;1573;1591</NoWarn>
        <Configurations>Debug;Release;Development;Testing;Staging;Production</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Compliance.Redaction" Version="10.9.0" />
        <PackageReference Include="Microsoft.FeatureManagement" Version="4.7.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SystemUptimeTracker.Common\SystemUptimeTracker.Common.csproj" />
    </ItemGroup>

</Project>
